services:

  # reservation-back-app:
  #   container_name: reservation-back
  #   build: .
  #   volumes:
  #     - ./src:/app/src
  #     - ./tsconfig.json:/app/tsconfig.json
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - .env
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   depends_on:
  #     - mongo-db
    

  mongo-db:
    image: mongo:7.0.14
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo-user
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017

