services:

  mongo-db:
    image: mongo:7.0.14
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo-user
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
